import { CSSVariableItem, CSSVariableCategory } from '../types';

/**
 * Categorize a CSS variable based on its name and value
 */
export function detectCategory(name: string, value: string): CSSVariableCategory {
  const n = name.toLowerCase();
  const v = value.toLowerCase().trim();

  if (
    n.includes('color') ||
    n.includes('bg') ||
    n.includes('accent') ||
    n.includes('glow') ||
    n.includes('surface') ||
    n.includes('tint') ||
    n.includes('fill') ||
    v.startsWith('#') ||
    v.startsWith('rgb') ||
    v.startsWith('hsl')
  ) {
    return 'colors';
  }

  if (
    n.includes('font') ||
    n.includes('typography') ||
    n.includes('line-height') ||
    n.includes('letter-spacing') ||
    n.includes('weight') ||
    v.includes('sans-serif') ||
    v.includes('serif') ||
    v.includes('monospace')
  ) {
    return 'typography';
  }

  if (
    n.includes('radius') ||
    n.includes('rounded') ||
    n.includes('border-width')
  ) {
    return 'borders';
  }

  if (n.includes('shadow') || n.includes('elevation') || n.includes('blur')) {
    return 'shadows';
  }

  if (
    n.includes('space') ||
    n.includes('spacing') ||
    n.includes('padding') ||
    n.includes('margin') ||
    n.includes('gap') ||
    n.includes('container') ||
    n.includes('width') ||
    n.includes('height')
  ) {
    return 'spacing';
  }

  return 'other';
}

/**
 * Extract CSS variables declared within :root { ... } from a stylesheet content
 */
export function extractCssVariables(cssContent: string): CSSVariableItem[] {
  const variables: CSSVariableItem[] = [];
  if (!cssContent) return variables;

  // Find all :root { ... } blocks
  const rootRegex = /:root\s*\{([^}]+)\}/g;
  let match: RegExpExecArray | null;

  while ((match = rootRegex.exec(cssContent)) !== null) {
    const blockContent = match[1];
    // Match --var-name: value;
    const varRegex = /(--[a-zA-Z0-9_-]+)\s*:\s*([^;]+);/g;
    let varMatch: RegExpExecArray | null;

    while ((varMatch = varRegex.exec(blockContent)) !== null) {
      const name = varMatch[1].trim();
      const value = varMatch[2].trim();
      const category = detectCategory(name, value);

      // Generate human-friendly label
      const cleanLabel = name
        .replace(/^--/, '')
        .split('-')
        .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
        .join(' ');

      // Avoid duplicates
      const exists = variables.find((v) => v.name === name);
      if (!exists) {
        variables.push({
          id: 'var_' + Math.random().toString(36).substring(2, 9),
          name,
          value,
          category,
          label: cleanLabel,
          type:
            category === 'colors'
              ? 'color'
              : category === 'typography'
              ? value.includes('sans') || value.includes('serif')
                ? 'font'
                : 'dimension'
              : category === 'shadows'
              ? 'shadow'
              : 'dimension',
        });
      }
    }
  }

  return variables;
}

/**
 * Format CSS variables into a clean, categorized :root { ... } block
 */
export function generateRootCssBlock(variables: CSSVariableItem[]): string {
  const grouped: Record<CSSVariableCategory, CSSVariableItem[]> = {
    colors: [],
    typography: [],
    spacing: [],
    borders: [],
    shadows: [],
    other: [],
  };

  for (const v of variables) {
    if (grouped[v.category]) {
      grouped[v.category].push(v);
    } else {
      grouped.other.push(v);
    }
  }

  let output = '/* ==========================================================================\n';
  output += '   Theme Tokens & Design System Variables (Generated by NONONICK Theme Studio)\n';
  output += '   ========================================================================== */\n';
  output += ':root {\n';

  const categoryTitles: Record<CSSVariableCategory, string> = {
    colors: 'Colors & Glow Accents',
    typography: 'Typography & Scale',
    spacing: 'Spacing & Container Layout',
    borders: 'Borders & Corner Radii',
    shadows: 'Shadows & Depth',
    other: 'Custom Tokens',
  };

  for (const cat of ['colors', 'typography', 'spacing', 'borders', 'shadows', 'other'] as CSSVariableCategory[]) {
    const list = grouped[cat];
    if (list.length > 0) {
      output += `  /* --- ${categoryTitles[cat]} --- */\n`;
      for (const item of list) {
        output += `  ${item.name}: ${item.value};\n`;
      }
      output += '\n';
    }
  }

  output = output.trimEnd() + '\n}\n';
  return output;
}

/**
 * Apply or replace the :root block in an existing CSS string
 */
export function applyVariablesToCssContent(existingCss: string, variables: CSSVariableItem[]): string {
  const newRootBlock = generateRootCssBlock(variables);

  // If a :root block exists, replace it
  const rootRegex = /(\/\*[\s\S]*?\*\/)?\s*:root\s*\{[\s\S]*?\}/;
  if (rootRegex.test(existingCss)) {
    return existingCss.replace(rootRegex, newRootBlock);
  }

  // Otherwise prepend it to the top
  return newRootBlock + '\n' + existingCss;
}

/**
 * Ensure an HTML document includes Google Fonts and stylesheet references
 */
export function ensureGoogleFontsAndCssInHtml(
  htmlContent: string,
  cssFilePath: string,
  fontFamilies: string[]
): string {
  let doc = htmlContent;

  // 1. Check for CSS link
  const cleanCssPath = cssFilePath.replace(/^\/+/, '');
  const cssRegex = new RegExp(`<link[^>]+href=["'][^"']*${cleanCssPath}["'][^>]*>`, 'i');
  if (!cssRegex.test(doc)) {
    const linkTag = `<link rel="stylesheet" href="${cleanCssPath}">`;
    if (doc.includes('</head>')) {
      doc = doc.replace('</head>', `  ${linkTag}\n</head>`);
    }
  }

  // 2. Google Fonts preconnect and links
  const validFonts = fontFamilies
    .map((f) => f.replace(/['"]/g, '').replace(/,.*$/, '').trim())
    .filter((f) => f && f !== 'system-ui' && f !== 'sans-serif' && f !== 'serif' && f !== 'monospace');

  const uniqueFonts = Array.from(new Set(validFonts));
  if (uniqueFonts.length > 0) {
    const fontParams = uniqueFonts.map((f) => `family=${encodeURIComponent(f)}:wght@300;400;500;600;700;800`).join('&');
    const googleFontUrl = `https://fonts.googleapis.com/css2?${fontParams}&display=swap`;

    // Only inject if not already present
    if (!doc.includes(googleFontUrl) && !doc.includes(uniqueFonts[0])) {
      const fontTags = `  <link rel="preconnect" href="https://fonts.googleapis.com">\n  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n  <link href="${googleFontUrl}" rel="stylesheet">\n`;
      if (doc.includes('</head>')) {
        doc = doc.replace('</head>', `${fontTags}</head>`);
      }
    }
  }

  return doc;
}

/**
 * Generate Tailwind configuration snippet extending the theme with these variables
 */
export function generateTailwindThemeExtension(variables: CSSVariableItem[]): string {
  const colors = variables.filter((v) => v.category === 'colors');
  const typography = variables.filter((v) => v.category === 'typography');

  let code = `/**\n * Tailwind CSS configuration extension for project variables\n * Add to tailwind.config.js or tailwind.config.ts\n */\nmodule.exports = {\n  theme: {\n    extend: {\n      colors: {\n`;

  for (const c of colors) {
    const cleanKey = c.name.replace(/^--color-/, '').replace(/^--/, '');
    code += `        '${cleanKey}': 'var(${c.name})',\n`;
  }

  code += `      },\n      fontFamily: {\n`;

  for (const t of typography) {
    if (t.type === 'font') {
      const cleanKey = t.name.replace(/^--font-/, '').replace(/^--/, '');
      code += `        '${cleanKey}': ['var(${t.name})'],\n`;
    }
  }

  code += `      },\n    },\n  },\n};\n`;
  return code;
}
