import { CSSVariableItem } from '../types';

export interface ThemePreset {
  id: string;
  name: string;
  nameFa: string;
  description: string;
  previewColors: string[];
  isDark: boolean;
  variables: CSSVariableItem[];
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'cyber-cyan',
    name: 'Apex Cyber Cyan',
    nameFa: 'سایبر سایان آپکس',
    description: 'Electric cyan, deep indigo ambient lighting, and sleek modern card glassmorphism',
    previewColors: ['#00f2fe', '#7928ca', '#090b11', '#f8fafc'],
    isDark: true,
    variables: [
      { id: 'v1', name: '--color-primary', value: '#00f2fe', category: 'colors', label: 'Primary Brand Color', type: 'color' },
      { id: 'v2', name: '--color-secondary', value: '#7928ca', category: 'colors', label: 'Secondary Accent', type: 'color' },
      { id: 'v3', name: '--color-accent-glow', value: 'rgba(0, 242, 254, 0.4)', category: 'colors', label: 'Glow Reflection', type: 'color' },
      { id: 'v4', name: '--color-bg', value: '#090b11', category: 'colors', label: 'Background Body', type: 'color' },
      { id: 'v5', name: '--color-surface', value: 'rgba(255, 255, 255, 0.04)', category: 'colors', label: 'Card Surface', type: 'color' },
      { id: 'v6', name: '--color-border', value: 'rgba(255, 255, 255, 0.08)', category: 'colors', label: 'Border Line', type: 'color' },
      { id: 'v7', name: '--color-text-main', value: '#f8fafc', category: 'colors', label: 'Heading & Body Text', type: 'color' },
      { id: 'v8', name: '--color-text-muted', value: '#94a3b8', category: 'colors', label: 'Muted Text', type: 'color' },
      { id: 'v9', name: '--color-success', value: '#10b981', category: 'colors', label: 'Success State', type: 'color' },
      { id: 'v10', name: '--color-warning', value: '#f59e0b', category: 'colors', label: 'Warning State', type: 'color' },
      { id: 'v11', name: '--color-danger', value: '#ef4444', category: 'colors', label: 'Danger / Error State', type: 'color' },
      { id: 'v12', name: '--font-heading', value: "'Plus Jakarta Sans', sans-serif", category: 'typography', label: 'Heading Font Family', type: 'font' },
      { id: 'v13', name: '--font-body', value: "'Plus Jakarta Sans', sans-serif", category: 'typography', label: 'Body Font Family', type: 'font' },
      { id: 'v14', name: '--font-size-base', value: '16px', category: 'typography', label: 'Base Font Size', type: 'dimension' },
      { id: 'v15', name: '--font-size-h1', value: '3.5rem', category: 'typography', label: 'H1 Display Size', type: 'dimension' },
      { id: 'v16', name: '--font-size-h2', value: '2.25rem', category: 'typography', label: 'H2 Section Size', type: 'dimension' },
      { id: 'v17', name: '--font-size-h3', value: '1.5rem', category: 'typography', label: 'H3 Card Title Size', type: 'dimension' },
      { id: 'v18', name: '--line-height-base', value: '1.6', category: 'typography', label: 'Body Line Height', type: 'number' },
      { id: 'v19', name: '--line-height-heading', value: '1.15', category: 'typography', label: 'Heading Line Height', type: 'number' },
      { id: 'v20', name: '--spacing-unit', value: '8px', category: 'spacing', label: 'Base Spacing Unit', type: 'dimension' },
      { id: 'v21', name: '--space-xs', value: '4px', category: 'spacing', label: 'Extra Small Spacing', type: 'dimension' },
      { id: 'v22', name: '--space-sm', value: '8px', category: 'spacing', label: 'Small Spacing', type: 'dimension' },
      { id: 'v23', name: '--space-md', value: '16px', category: 'spacing', label: 'Medium Spacing', type: 'dimension' },
      { id: 'v24', name: '--space-lg', value: '24px', category: 'spacing', label: 'Large Spacing', type: 'dimension' },
      { id: 'v25', name: '--space-xl', value: '40px', category: 'spacing', label: 'Extra Large Spacing', type: 'dimension' },
      { id: 'v26', name: '--radius-sm', value: '6px', category: 'borders', label: 'Border Radius Small', type: 'dimension' },
      { id: 'v27', name: '--radius-md', value: '12px', category: 'borders', label: 'Border Radius Medium', type: 'dimension' },
      { id: 'v28', name: '--radius-lg', value: '20px', category: 'borders', label: 'Border Radius Large', type: 'dimension' },
      { id: 'v29', name: '--radius-full', value: '9999px', category: 'borders', label: 'Rounded Pill Radius', type: 'dimension' },
      { id: 'v30', name: '--container-max-width', value: '1280px', category: 'spacing', label: 'Container Max Width', type: 'dimension' },
      { id: 'v31', name: '--shadow-card', value: '0 8px 32px 0 rgba(0, 0, 0, 0.37)', category: 'shadows', label: 'Card Elevation Shadow', type: 'shadow' },
      { id: 'v32', name: '--shadow-glow', value: '0 0 24px rgba(0, 242, 254, 0.35)', category: 'shadows', label: 'Interactive Glow', type: 'shadow' },
    ],
  },
  {
    id: 'midnight-nebula',
    name: 'Midnight Nebula',
    nameFa: 'سحابی بنفش شبانه',
    description: 'Deep violet dark space, radiant magenta-purple neon, and fluid modern curves',
    previewColors: ['#a855f7', '#ec4899', '#070712', '#faf5ff'],
    isDark: true,
    variables: [
      { id: 'v1', name: '--color-primary', value: '#a855f7', category: 'colors', label: 'Primary Brand Color', type: 'color' },
      { id: 'v2', name: '--color-secondary', value: '#ec4899', category: 'colors', label: 'Secondary Accent', type: 'color' },
      { id: 'v3', name: '--color-accent-glow', value: 'rgba(168, 85, 247, 0.45)', category: 'colors', label: 'Glow Reflection', type: 'color' },
      { id: 'v4', name: '--color-bg', value: '#070712', category: 'colors', label: 'Background Body', type: 'color' },
      { id: 'v5', name: '--color-surface', value: 'rgba(30, 20, 50, 0.5)', category: 'colors', label: 'Card Surface', type: 'color' },
      { id: 'v6', name: '--color-border', value: 'rgba(168, 85, 247, 0.2)', category: 'colors', label: 'Border Line', type: 'color' },
      { id: 'v7', name: '--color-text-main', value: '#faf5ff', category: 'colors', label: 'Heading & Body Text', type: 'color' },
      { id: 'v8', name: '--color-text-muted', value: '#c084fc', category: 'colors', label: 'Muted Text', type: 'color' },
      { id: 'v9', name: '--color-success', value: '#34d399', category: 'colors', label: 'Success State', type: 'color' },
      { id: 'v10', name: '--color-warning', value: '#fbbf24', category: 'colors', label: 'Warning State', type: 'color' },
      { id: 'v11', name: '--color-danger', value: '#f43f5e', category: 'colors', label: 'Danger / Error State', type: 'color' },
      { id: 'v12', name: '--font-heading', value: "'Outfit', sans-serif", category: 'typography', label: 'Heading Font Family', type: 'font' },
      { id: 'v13', name: '--font-body', value: "'Inter', sans-serif", category: 'typography', label: 'Body Font Family', type: 'font' },
      { id: 'v14', name: '--font-size-base', value: '16px', category: 'typography', label: 'Base Font Size', type: 'dimension' },
      { id: 'v15', name: '--font-size-h1', value: '3.75rem', category: 'typography', label: 'H1 Display Size', type: 'dimension' },
      { id: 'v16', name: '--font-size-h2', value: '2.5rem', category: 'typography', label: 'H2 Section Size', type: 'dimension' },
      { id: 'v17', name: '--font-size-h3', value: '1.6rem', category: 'typography', label: 'H3 Card Title Size', type: 'dimension' },
      { id: 'v18', name: '--line-height-base', value: '1.65', category: 'typography', label: 'Body Line Height', type: 'number' },
      { id: 'v19', name: '--line-height-heading', value: '1.1', category: 'typography', label: 'Heading Line Height', type: 'number' },
      { id: 'v20', name: '--spacing-unit', value: '8px', category: 'spacing', label: 'Base Spacing Unit', type: 'dimension' },
      { id: 'v21', name: '--space-xs', value: '4px', category: 'spacing', label: 'Extra Small Spacing', type: 'dimension' },
      { id: 'v22', name: '--space-sm', value: '8px', category: 'spacing', label: 'Small Spacing', type: 'dimension' },
      { id: 'v23', name: '--space-md', value: '16px', category: 'spacing', label: 'Medium Spacing', type: 'dimension' },
      { id: 'v24', name: '--space-lg', value: '24px', category: 'spacing', label: 'Large Spacing', type: 'dimension' },
      { id: 'v25', name: '--space-xl', value: '48px', category: 'spacing', label: 'Extra Large Spacing', type: 'dimension' },
      { id: 'v26', name: '--radius-sm', value: '8px', category: 'borders', label: 'Border Radius Small', type: 'dimension' },
      { id: 'v27', name: '--radius-md', value: '16px', category: 'borders', label: 'Border Radius Medium', type: 'dimension' },
      { id: 'v28', name: '--radius-lg', value: '28px', category: 'borders', label: 'Border Radius Large', type: 'dimension' },
      { id: 'v29', name: '--radius-full', value: '9999px', category: 'borders', label: 'Rounded Pill Radius', type: 'dimension' },
      { id: 'v30', name: '--container-max-width', value: '1240px', category: 'spacing', label: 'Container Max Width', type: 'dimension' },
      { id: 'v31', name: '--shadow-card', value: '0 12px 40px 0 rgba(7, 3, 20, 0.6)', category: 'shadows', label: 'Card Elevation Shadow', type: 'shadow' },
      { id: 'v32', name: '--shadow-glow', value: '0 0 30px rgba(168, 85, 247, 0.4)', category: 'shadows', label: 'Interactive Glow', type: 'shadow' },
    ],
  },
  {
    id: 'emerald-fintech',
    name: 'Emerald Minimal',
    nameFa: 'سبز زمردی مینیمال',
    description: 'Fresh emerald green, deep pine contrast, clean typography for fintech & data products',
    previewColors: ['#10b981', '#06b6d4', '#06120d', '#ecfdf5'],
    isDark: true,
    variables: [
      { id: 'v1', name: '--color-primary', value: '#10b981', category: 'colors', label: 'Primary Brand Color', type: 'color' },
      { id: 'v2', name: '--color-secondary', value: '#06b6d4', category: 'colors', label: 'Secondary Accent', type: 'color' },
      { id: 'v3', name: '--color-accent-glow', value: 'rgba(16, 185, 129, 0.35)', category: 'colors', label: 'Glow Reflection', type: 'color' },
      { id: 'v4', name: '--color-bg', value: '#06120d', category: 'colors', label: 'Background Body', type: 'color' },
      { id: 'v5', name: '--color-surface', value: 'rgba(16, 185, 129, 0.05)', category: 'colors', label: 'Card Surface', type: 'color' },
      { id: 'v6', name: '--color-border', value: 'rgba(16, 185, 129, 0.16)', category: 'colors', label: 'Border Line', type: 'color' },
      { id: 'v7', name: '--color-text-main', value: '#ecfdf5', category: 'colors', label: 'Heading & Body Text', type: 'color' },
      { id: 'v8', name: '--color-text-muted', value: '#6ee7b7', category: 'colors', label: 'Muted Text', type: 'color' },
      { id: 'v9', name: '--color-success', value: '#10b981', category: 'colors', label: 'Success State', type: 'color' },
      { id: 'v10', name: '--color-warning', value: '#fbbf24', category: 'colors', label: 'Warning State', type: 'color' },
      { id: 'v11', name: '--color-danger', value: '#f87171', category: 'colors', label: 'Danger / Error State', type: 'color' },
      { id: 'v12', name: '--font-heading', value: "'Inter', sans-serif", category: 'typography', label: 'Heading Font Family', type: 'font' },
      { id: 'v13', name: '--font-body', value: "'Inter', sans-serif", category: 'typography', label: 'Body Font Family', type: 'font' },
      { id: 'v14', name: '--font-size-base', value: '15px', category: 'typography', label: 'Base Font Size', type: 'dimension' },
      { id: 'v15', name: '--font-size-h1', value: '3.25rem', category: 'typography', label: 'H1 Display Size', type: 'dimension' },
      { id: 'v16', name: '--font-size-h2', value: '2.1rem', category: 'typography', label: 'H2 Section Size', type: 'dimension' },
      { id: 'v17', name: '--font-size-h3', value: '1.4rem', category: 'typography', label: 'H3 Card Title Size', type: 'dimension' },
      { id: 'v18', name: '--line-height-base', value: '1.6', category: 'typography', label: 'Body Line Height', type: 'number' },
      { id: 'v19', name: '--line-height-heading', value: '1.2', category: 'typography', label: 'Heading Line Height', type: 'number' },
      { id: 'v20', name: '--spacing-unit', value: '8px', category: 'spacing', label: 'Base Spacing Unit', type: 'dimension' },
      { id: 'v21', name: '--space-xs', value: '4px', category: 'spacing', label: 'Extra Small Spacing', type: 'dimension' },
      { id: 'v22', name: '--space-sm', value: '8px', category: 'spacing', label: 'Small Spacing', type: 'dimension' },
      { id: 'v23', name: '--space-md', value: '16px', category: 'spacing', label: 'Medium Spacing', type: 'dimension' },
      { id: 'v24', name: '--space-lg', value: '24px', category: 'spacing', label: 'Large Spacing', type: 'dimension' },
      { id: 'v25', name: '--space-xl', value: '40px', category: 'spacing', label: 'Extra Large Spacing', type: 'dimension' },
      { id: 'v26', name: '--radius-sm', value: '6px', category: 'borders', label: 'Border Radius Small', type: 'dimension' },
      { id: 'v27', name: '--radius-md', value: '10px', category: 'borders', label: 'Border Radius Medium', type: 'dimension' },
      { id: 'v28', name: '--radius-lg', value: '16px', category: 'borders', label: 'Border Radius Large', type: 'dimension' },
      { id: 'v29', name: '--radius-full', value: '9999px', category: 'borders', label: 'Rounded Pill Radius', type: 'dimension' },
      { id: 'v30', name: '--container-max-width', value: '1200px', category: 'spacing', label: 'Container Max Width', type: 'dimension' },
      { id: 'v31', name: '--shadow-card', value: '0 4px 20px 0 rgba(0, 0, 0, 0.4)', category: 'shadows', label: 'Card Elevation Shadow', type: 'shadow' },
      { id: 'v32', name: '--shadow-glow', value: '0 0 20px rgba(16, 185, 129, 0.3)', category: 'shadows', label: 'Interactive Glow', type: 'shadow' },
    ],
  },
  {
    id: 'sunset-amber',
    name: 'Sunset Warmth & Coral',
    nameFa: 'غروب گرم و کهربایی',
    description: 'Warm amber, soft coral gradients, and welcoming modern aesthetic for creators and startups',
    previewColors: ['#f59e0b', '#f43f5e', '#0f0e17', '#fffffe'],
    isDark: true,
    variables: [
      { id: 'v1', name: '--color-primary', value: '#f59e0b', category: 'colors', label: 'Primary Brand Color', type: 'color' },
      { id: 'v2', name: '--color-secondary', value: '#f43f5e', category: 'colors', label: 'Secondary Accent', type: 'color' },
      { id: 'v3', name: '--color-accent-glow', value: 'rgba(245, 158, 11, 0.4)', category: 'colors', label: 'Glow Reflection', type: 'color' },
      { id: 'v4', name: '--color-bg', value: '#0f0e17', category: 'colors', label: 'Background Body', type: 'color' },
      { id: 'v5', name: '--color-surface', value: 'rgba(255, 255, 255, 0.05)', category: 'colors', label: 'Card Surface', type: 'color' },
      { id: 'v6', name: '--color-border', value: 'rgba(245, 158, 11, 0.18)', category: 'colors', label: 'Border Line', type: 'color' },
      { id: 'v7', name: '--color-text-main', value: '#fffffe', category: 'colors', label: 'Heading & Body Text', type: 'color' },
      { id: 'v8', name: '--color-text-muted', value: '#a7a9be', category: 'colors', label: 'Muted Text', type: 'color' },
      { id: 'v9', name: '--color-success', value: '#10b981', category: 'colors', label: 'Success State', type: 'color' },
      { id: 'v10', name: '--color-warning', value: '#f59e0b', category: 'colors', label: 'Warning State', type: 'color' },
      { id: 'v11', name: '--color-danger', value: '#ef4444', category: 'colors', label: 'Danger / Error State', type: 'color' },
      { id: 'v12', name: '--font-heading', value: "'Poppins', sans-serif", category: 'typography', label: 'Heading Font Family', type: 'font' },
      { id: 'v13', name: '--font-body', value: "'Poppins', sans-serif", category: 'typography', label: 'Body Font Family', type: 'font' },
      { id: 'v14', name: '--font-size-base', value: '16px', category: 'typography', label: 'Base Font Size', type: 'dimension' },
      { id: 'v15', name: '--font-size-h1', value: '3.5rem', category: 'typography', label: 'H1 Display Size', type: 'dimension' },
      { id: 'v16', name: '--font-size-h2', value: '2.25rem', category: 'typography', label: 'H2 Section Size', type: 'dimension' },
      { id: 'v17', name: '--font-size-h3', value: '1.5rem', category: 'typography', label: 'H3 Card Title Size', type: 'dimension' },
      { id: 'v18', name: '--line-height-base', value: '1.6', category: 'typography', label: 'Body Line Height', type: 'number' },
      { id: 'v19', name: '--line-height-heading', value: '1.15', category: 'typography', label: 'Heading Line Height', type: 'number' },
      { id: 'v20', name: '--spacing-unit', value: '8px', category: 'spacing', label: 'Base Spacing Unit', type: 'dimension' },
      { id: 'v21', name: '--space-xs', value: '4px', category: 'spacing', label: 'Extra Small Spacing', type: 'dimension' },
      { id: 'v22', name: '--space-sm', value: '8px', category: 'spacing', label: 'Small Spacing', type: 'dimension' },
      { id: 'v23', name: '--space-md', value: '16px', category: 'spacing', label: 'Medium Spacing', type: 'dimension' },
      { id: 'v24', name: '--space-lg', value: '24px', category: 'spacing', label: 'Large Spacing', type: 'dimension' },
      { id: 'v25', name: '--space-xl', value: '44px', category: 'spacing', label: 'Extra Large Spacing', type: 'dimension' },
      { id: 'v26', name: '--radius-sm', value: '8px', category: 'borders', label: 'Border Radius Small', type: 'dimension' },
      { id: 'v27', name: '--radius-md', value: '14px', category: 'borders', label: 'Border Radius Medium', type: 'dimension' },
      { id: 'v28', name: '--radius-lg', value: '24px', category: 'borders', label: 'Border Radius Large', type: 'dimension' },
      { id: 'v29', name: '--radius-full', value: '9999px', category: 'borders', label: 'Rounded Pill Radius', type: 'dimension' },
      { id: 'v30', name: '--container-max-width', value: '1280px', category: 'spacing', label: 'Container Max Width', type: 'dimension' },
      { id: 'v31', name: '--shadow-card', value: '0 8px 30px rgba(0, 0, 0, 0.45)', category: 'shadows', label: 'Card Elevation Shadow', type: 'shadow' },
      { id: 'v32', name: '--shadow-glow', value: '0 0 25px rgba(245, 158, 11, 0.35)', category: 'shadows', label: 'Interactive Glow', type: 'shadow' },
    ],
  },
  {
    id: 'persian-modern',
    name: 'Persian Azure & Saffron',
    nameFa: 'مدرن فیروزه‌ای و زعفرانی (وزیرمتن)',
    description: 'Iranian turquoise, saffron highlights, optimized for Persian/Arabic typography and modern layouts',
    previewColors: ['#06b6d4', '#f59e0b', '#07151e', '#f0fdfa'],
    isDark: true,
    variables: [
      { id: 'v1', name: '--color-primary', value: '#06b6d4', category: 'colors', label: 'رنگ اصلی (فیروزه‌ای)', type: 'color' },
      { id: 'v2', name: '--color-secondary', value: '#f59e0b', category: 'colors', label: 'رنگ ثانویه (زعفرانی)', type: 'color' },
      { id: 'v3', name: '--color-accent-glow', value: 'rgba(6, 182, 212, 0.38)', category: 'colors', label: 'درخشش المان‌ها', type: 'color' },
      { id: 'v4', name: '--color-bg', value: '#07151e', category: 'colors', label: 'پس‌زمینه صفحه', type: 'color' },
      { id: 'v5', name: '--color-surface', value: 'rgba(6, 182, 212, 0.05)', category: 'colors', label: 'کارت‌ها و پنل‌ها', type: 'color' },
      { id: 'v6', name: '--color-border', value: 'rgba(6, 182, 212, 0.16)', category: 'colors', label: 'خطوط و حاشیه‌ها', type: 'color' },
      { id: 'v7', name: '--color-text-main', value: '#f0fdfa', category: 'colors', label: 'متن اصلی', type: 'color' },
      { id: 'v8', name: '--color-text-muted', value: '#99f6e4', category: 'colors', label: 'متن فرعی و توضیحات', type: 'color' },
      { id: 'v9', name: '--color-success', value: '#10b981', category: 'colors', label: 'وضعیت موفقیت', type: 'color' },
      { id: 'v10', name: '--color-warning', value: '#f59e0b', category: 'colors', label: 'وضعیت هشدار', type: 'color' },
      { id: 'v11', name: '--color-danger', value: '#ef4444', category: 'colors', label: 'وضعیت خطا', type: 'color' },
      { id: 'v12', name: '--font-heading', value: "'Vazirmatn', sans-serif", category: 'typography', label: 'فونت سرتیترها', type: 'font' },
      { id: 'v13', name: '--font-body', value: "'Vazirmatn', sans-serif", category: 'typography', label: 'فونت متن اصلی', type: 'font' },
      { id: 'v14', name: '--font-size-base', value: '16px', category: 'typography', label: 'اندازه پایه متن', type: 'dimension' },
      { id: 'v15', name: '--font-size-h1', value: '3.2rem', category: 'typography', label: 'اندازه عنوان بزرگ H1', type: 'dimension' },
      { id: 'v16', name: '--font-size-h2', value: '2.1rem', category: 'typography', label: 'اندازه سرتیتر H2', type: 'dimension' },
      { id: 'v17', name: '--font-size-h3', value: '1.45rem', category: 'typography', label: 'اندازه عنوان کارت H3', type: 'dimension' },
      { id: 'v18', name: '--line-height-base', value: '1.7', category: 'typography', label: 'فاصله خطوط متن', type: 'number' },
      { id: 'v19', name: '--line-height-heading', value: '1.25', category: 'typography', label: 'فاصله خطوط عنوان', type: 'number' },
      { id: 'v20', name: '--spacing-unit', value: '8px', category: 'spacing', label: 'واحد فاصله پایه', type: 'dimension' },
      { id: 'v21', name: '--space-xs', value: '4px', category: 'spacing', label: 'فاصله خیلی کم', type: 'dimension' },
      { id: 'v22', name: '--space-sm', value: '8px', category: 'spacing', label: 'فاصله کم', type: 'dimension' },
      { id: 'v23', name: '--space-md', value: '16px', category: 'spacing', label: 'فاصله متوسط', type: 'dimension' },
      { id: 'v24', name: '--space-lg', value: '24px', category: 'spacing', label: 'فاصله زیاد', type: 'dimension' },
      { id: 'v25', name: '--space-xl', value: '44px', category: 'spacing', label: 'فاصله خیلی زیاد', type: 'dimension' },
      { id: 'v26', name: '--radius-sm', value: '6px', category: 'borders', label: 'گردی لبه کوچک', type: 'dimension' },
      { id: 'v27', name: '--radius-md', value: '12px', category: 'borders', label: 'گردی لبه متوسط', type: 'dimension' },
      { id: 'v28', name: '--radius-lg', value: '20px', category: 'borders', label: 'گردی لبه بزرگ', type: 'dimension' },
      { id: 'v29', name: '--radius-full', value: '9999px', category: 'borders', label: 'گردی کامل دکمه', type: 'dimension' },
      { id: 'v30', name: '--container-max-width', value: '1260px', category: 'spacing', label: 'حداکثر عرض نگهدارنده', type: 'dimension' },
      { id: 'v31', name: '--shadow-card', value: '0 8px 30px rgba(0, 0, 0, 0.4)', category: 'shadows', label: 'سایه کارت‌ها', type: 'shadow' },
      { id: 'v32', name: '--shadow-glow', value: '0 0 24px rgba(6, 182, 212, 0.35)', category: 'shadows', label: 'درخشش المان‌ها', type: 'shadow' },
    ],
  },
  {
    id: 'luxury-gold',
    name: 'Luxury Obsidian & Gold',
    nameFa: 'طلایی لوکس و ابسیدین',
    description: 'Metallic champagne gold accents, obsidian black noir, and editorial serif elegance',
    previewColors: ['#d4af37', '#e6ca65', '#0a0a0d', '#fdfbf7'],
    isDark: true,
    variables: [
      { id: 'v1', name: '--color-primary', value: '#d4af37', category: 'colors', label: 'Primary Metallic Gold', type: 'color' },
      { id: 'v2', name: '--color-secondary', value: '#e6ca65', category: 'colors', label: 'Secondary Champagne', type: 'color' },
      { id: 'v3', name: '--color-accent-glow', value: 'rgba(212, 175, 55, 0.35)', category: 'colors', label: 'Gold Glow', type: 'color' },
      { id: 'v4', name: '--color-bg', value: '#0a0a0d', category: 'colors', label: 'Background Body', type: 'color' },
      { id: 'v5', name: '--color-surface', value: 'rgba(25, 25, 30, 0.8)', category: 'colors', label: 'Card Surface', type: 'color' },
      { id: 'v6', name: '--color-border', value: 'rgba(212, 175, 55, 0.22)', category: 'colors', label: 'Border Line', type: 'color' },
      { id: 'v7', name: '--color-text-main', value: '#fdfbf7', category: 'colors', label: 'Heading & Body Text', type: 'color' },
      { id: 'v8', name: '--color-text-muted', value: '#a8a29e', category: 'colors', label: 'Muted Text', type: 'color' },
      { id: 'v9', name: '--color-success', value: '#10b981', category: 'colors', label: 'Success State', type: 'color' },
      { id: 'v10', name: '--color-warning', value: '#d4af37', category: 'colors', label: 'Warning State', type: 'color' },
      { id: 'v11', name: '--color-danger', value: '#e11d48', category: 'colors', label: 'Danger / Error State', type: 'color' },
      { id: 'v12', name: '--font-heading', value: "'Playfair Display', serif", category: 'typography', label: 'Heading Font Family', type: 'font' },
      { id: 'v13', name: '--font-body', value: "'Inter', sans-serif", category: 'typography', label: 'Body Font Family', type: 'font' },
      { id: 'v14', name: '--font-size-base', value: '16px', category: 'typography', label: 'Base Font Size', type: 'dimension' },
      { id: 'v15', name: '--font-size-h1', value: '3.75rem', category: 'typography', label: 'H1 Display Size', type: 'dimension' },
      { id: 'v16', name: '--font-size-h2', value: '2.4rem', category: 'typography', label: 'H2 Section Size', type: 'dimension' },
      { id: 'v17', name: '--font-size-h3', value: '1.5rem', category: 'typography', label: 'H3 Card Title Size', type: 'dimension' },
      { id: 'v18', name: '--line-height-base', value: '1.65', category: 'typography', label: 'Body Line Height', type: 'number' },
      { id: 'v19', name: '--line-height-heading', value: '1.15', category: 'typography', label: 'Heading Line Height', type: 'number' },
      { id: 'v20', name: '--spacing-unit', value: '8px', category: 'spacing', label: 'Base Spacing Unit', type: 'dimension' },
      { id: 'v21', name: '--space-xs', value: '4px', category: 'spacing', label: 'Extra Small Spacing', type: 'dimension' },
      { id: 'v22', name: '--space-sm', value: '8px', category: 'spacing', label: 'Small Spacing', type: 'dimension' },
      { id: 'v23', name: '--space-md', value: '16px', category: 'spacing', label: 'Medium Spacing', type: 'dimension' },
      { id: 'v24', name: '--space-lg', value: '24px', category: 'spacing', label: 'Large Spacing', type: 'dimension' },
      { id: 'v25', name: '--space-xl', value: '48px', category: 'spacing', label: 'Extra Large Spacing', type: 'dimension' },
      { id: 'v26', name: '--radius-sm', value: '4px', category: 'borders', label: 'Border Radius Small', type: 'dimension' },
      { id: 'v27', name: '--radius-md', value: '8px', category: 'borders', label: 'Border Radius Medium', type: 'dimension' },
      { id: 'v28', name: '--radius-lg', value: '16px', category: 'borders', label: 'Border Radius Large', type: 'dimension' },
      { id: 'v29', name: '--radius-full', value: '9999px', category: 'borders', label: 'Rounded Pill Radius', type: 'dimension' },
      { id: 'v30', name: '--container-max-width', value: '1200px', category: 'spacing', label: 'Container Max Width', type: 'dimension' },
      { id: 'v31', name: '--shadow-card', value: '0 10px 40px rgba(0, 0, 0, 0.7)', category: 'shadows', label: 'Card Elevation Shadow', type: 'shadow' },
      { id: 'v32', name: '--shadow-glow', value: '0 0 25px rgba(212, 175, 55, 0.3)', category: 'shadows', label: 'Interactive Glow', type: 'shadow' },
    ],
  },
  {
    id: 'nordic-light',
    name: 'Nordic Clean Light',
    nameFa: 'نوردیک روشن و مدرن',
    description: 'Clean crisp light mode, calm oceanic blue accents, high legibility slate typography',
    previewColors: ['#0284c7', '#6366f1', '#f8fafc', '#0f172a'],
    isDark: false,
    variables: [
      { id: 'v1', name: '--color-primary', value: '#0284c7', category: 'colors', label: 'Primary Brand Color', type: 'color' },
      { id: 'v2', name: '--color-secondary', value: '#6366f1', category: 'colors', label: 'Secondary Accent', type: 'color' },
      { id: 'v3', name: '--color-accent-glow', value: 'rgba(2, 132, 199, 0.25)', category: 'colors', label: 'Glow Reflection', type: 'color' },
      { id: 'v4', name: '--color-bg', value: '#f8fafc', category: 'colors', label: 'Background Body', type: 'color' },
      { id: 'v5', name: '--color-surface', value: '#ffffff', category: 'colors', label: 'Card Surface', type: 'color' },
      { id: 'v6', name: '--color-border', value: '#e2e8f0', category: 'colors', label: 'Border Line', type: 'color' },
      { id: 'v7', name: '--color-text-main', value: '#0f172a', category: 'colors', label: 'Heading & Body Text', type: 'color' },
      { id: 'v8', name: '--color-text-muted', value: '#64748b', category: 'colors', label: 'Muted Text', type: 'color' },
      { id: 'v9', name: '--color-success', value: '#16a34a', category: 'colors', label: 'Success State', type: 'color' },
      { id: 'v10', name: '--color-warning', value: '#d97706', category: 'colors', label: 'Warning State', type: 'color' },
      { id: 'v11', name: '--color-danger', value: '#dc2626', category: 'colors', label: 'Danger / Error State', type: 'color' },
      { id: 'v12', name: '--font-heading', value: "'Inter', sans-serif", category: 'typography', label: 'Heading Font Family', type: 'font' },
      { id: 'v13', name: '--font-body', value: "'Inter', sans-serif", category: 'typography', label: 'Body Font Family', type: 'font' },
      { id: 'v14', name: '--font-size-base', value: '16px', category: 'typography', label: 'Base Font Size', type: 'dimension' },
      { id: 'v15', name: '--font-size-h1', value: '3.5rem', category: 'typography', label: 'H1 Display Size', type: 'dimension' },
      { id: 'v16', name: '--font-size-h2', value: '2.25rem', category: 'typography', label: 'H2 Section Size', type: 'dimension' },
      { id: 'v17', name: '--font-size-h3', value: '1.5rem', category: 'typography', label: 'H3 Card Title Size', type: 'dimension' },
      { id: 'v18', name: '--line-height-base', value: '1.6', category: 'typography', label: 'Body Line Height', type: 'number' },
      { id: 'v19', name: '--line-height-heading', value: '1.18', category: 'typography', label: 'Heading Line Height', type: 'number' },
      { id: 'v20', name: '--spacing-unit', value: '8px', category: 'spacing', label: 'Base Spacing Unit', type: 'dimension' },
      { id: 'v21', name: '--space-xs', value: '4px', category: 'spacing', label: 'Extra Small Spacing', type: 'dimension' },
      { id: 'v22', name: '--space-sm', value: '8px', category: 'spacing', label: 'Small Spacing', type: 'dimension' },
      { id: 'v23', name: '--space-md', value: '16px', category: 'spacing', label: 'Medium Spacing', type: 'dimension' },
      { id: 'v24', name: '--space-lg', value: '24px', category: 'spacing', label: 'Large Spacing', type: 'dimension' },
      { id: 'v25', name: '--space-xl', value: '40px', category: 'spacing', label: 'Extra Large Spacing', type: 'dimension' },
      { id: 'v26', name: '--radius-sm', value: '6px', category: 'borders', label: 'Border Radius Small', type: 'dimension' },
      { id: 'v27', name: '--radius-md', value: '12px', category: 'borders', label: 'Border Radius Medium', type: 'dimension' },
      { id: 'v28', name: '--radius-lg', value: '20px', category: 'borders', label: 'Border Radius Large', type: 'dimension' },
      { id: 'v29', name: '--radius-full', value: '9999px', category: 'borders', label: 'Rounded Pill Radius', type: 'dimension' },
      { id: 'v30', name: '--container-max-width', value: '1280px', category: 'spacing', label: 'Container Max Width', type: 'dimension' },
      { id: 'v31', name: '--shadow-card', value: '0 4px 20px -2px rgba(0, 0, 0, 0.08), 0 2px 6px -1px rgba(0, 0, 0, 0.04)', category: 'shadows', label: 'Card Elevation Shadow', type: 'shadow' },
      { id: 'v32', name: '--shadow-glow', value: '0 0 20px rgba(2, 132, 199, 0.25)', category: 'shadows', label: 'Interactive Glow', type: 'shadow' },
    ],
  },
  {
    id: 'brutalist-mono',
    name: 'Brutalist Monochrome',
    nameFa: 'بروتالیست تک‌رنگ و دقیق',
    description: 'High contrast stark black & white, sharp architectural 0px corners, and mono-grotesk typography',
    previewColors: ['#ffffff', '#888888', '#000000', '#f4f4f4'],
    isDark: true,
    variables: [
      { id: 'v1', name: '--color-primary', value: '#ffffff', category: 'colors', label: 'Primary Stark White', type: 'color' },
      { id: 'v2', name: '--color-secondary', value: '#94a3b8', category: 'colors', label: 'Secondary Steel Gray', type: 'color' },
      { id: 'v3', name: '--color-accent-glow', value: 'none', category: 'colors', label: 'Glow Reflection', type: 'color' },
      { id: 'v4', name: '--color-bg', value: '#000000', category: 'colors', label: 'Background Body', type: 'color' },
      { id: 'v5', name: '--color-surface', value: '#111111', category: 'colors', label: 'Card Surface', type: 'color' },
      { id: 'v6', name: '--color-border', value: '#333333', category: 'colors', label: 'Border Line', type: 'color' },
      { id: 'v7', name: '--color-text-main', value: '#ffffff', category: 'colors', label: 'Heading & Body Text', type: 'color' },
      { id: 'v8', name: '--color-text-muted', value: '#888888', category: 'colors', label: 'Muted Text', type: 'color' },
      { id: 'v9', name: '--color-success', value: '#ffffff', category: 'colors', label: 'Success State', type: 'color' },
      { id: 'v10', name: '--color-warning', value: '#cccccc', category: 'colors', label: 'Warning State', type: 'color' },
      { id: 'v11', name: '--color-danger', value: '#ff3333', category: 'colors', label: 'Danger / Error State', type: 'color' },
      { id: 'v12', name: '--font-heading', value: "'Space Grotesk', system-ui, sans-serif", category: 'typography', label: 'Heading Font Family', type: 'font' },
      { id: 'v13', name: '--font-body', value: "'Space Grotesk', monospace", category: 'typography', label: 'Body Font Family', type: 'font' },
      { id: 'v14', name: '--font-size-base', value: '15px', category: 'typography', label: 'Base Font Size', type: 'dimension' },
      { id: 'v15', name: '--font-size-h1', value: '4rem', category: 'typography', label: 'H1 Display Size', type: 'dimension' },
      { id: 'v16', name: '--font-size-h2', value: '2.5rem', category: 'typography', label: 'H2 Section Size', type: 'dimension' },
      { id: 'v17', name: '--font-size-h3', value: '1.5rem', category: 'typography', label: 'H3 Card Title Size', type: 'dimension' },
      { id: 'v18', name: '--line-height-base', value: '1.5', category: 'typography', label: 'Body Line Height', type: 'number' },
      { id: 'v19', name: '--line-height-heading', value: '1.0', category: 'typography', label: 'Heading Line Height', type: 'number' },
      { id: 'v20', name: '--spacing-unit', value: '8px', category: 'spacing', label: 'Base Spacing Unit', type: 'dimension' },
      { id: 'v21', name: '--space-xs', value: '4px', category: 'spacing', label: 'Extra Small Spacing', type: 'dimension' },
      { id: 'v22', name: '--space-sm', value: '8px', category: 'spacing', label: 'Small Spacing', type: 'dimension' },
      { id: 'v23', name: '--space-md', value: '16px', category: 'spacing', label: 'Medium Spacing', type: 'dimension' },
      { id: 'v24', name: '--space-lg', value: '24px', category: 'spacing', label: 'Large Spacing', type: 'dimension' },
      { id: 'v25', name: '--space-xl', value: '48px', category: 'spacing', label: 'Extra Large Spacing', type: 'dimension' },
      { id: 'v26', name: '--radius-sm', value: '0px', category: 'borders', label: 'Border Radius Small', type: 'dimension' },
      { id: 'v27', name: '--radius-md', value: '0px', category: 'borders', label: 'Border Radius Medium', type: 'dimension' },
      { id: 'v28', name: '--radius-lg', value: '0px', category: 'borders', label: 'Border Radius Large', type: 'dimension' },
      { id: 'v29', name: '--radius-full', value: '0px', category: 'borders', label: 'Sharp Pill Radius', type: 'dimension' },
      { id: 'v30', name: '--container-max-width', value: '1320px', category: 'spacing', label: 'Container Max Width', type: 'dimension' },
      { id: 'v31', name: '--shadow-card', value: '4px 4px 0px #333333', category: 'shadows', label: 'Card Elevation Shadow', type: 'shadow' },
      { id: 'v32', name: '--shadow-glow', value: 'none', category: 'shadows', label: 'Interactive Glow', type: 'shadow' },
    ],
  },
];
